// Pre-seeded demo data for investor presentations.
// The /demo route loads this directly — no API or AI calls needed for static views.
// Live chat still hits the real Anthropic API for impressive real-time demos.

export const DEMO_FAMILY = {
  id: "demo-family-001",
  name: "The Rivera Family",
  budget_weekly: 275,
  quality_preference: "mid_range",
  members: [
    {
      id: "demo-member-001",
      name: "Maria",
      age: 42,
      life_stage: "adult",
      sex: "female",
      activity_level: "moderately_active",
      dietary_style: "flexitarian",
      wellness_philosophy: "ayurvedic",
      dosha: "pitta",
      goals: ["Hormone balance", "Stress management", "Better sleep"],
      allergies: ["Gluten"],
      dislikes: ["Lamb", "Blue cheese"],
      loves: ["Avocado", "Dark leafy greens", "Mango"],
      cuisine_prefs: ["Mediterranean", "Indian", "Mexican"],
      health_conditions: ["Perimenopause"],
      current_supplements: ["Magnesium glycinate", "Vitamin D3"],
      supplements_open: true,
    },
    {
      id: "demo-member-002",
      name: "David",
      age: 45,
      life_stage: "adult",
      sex: "male",
      activity_level: "lightly_active",
      dietary_style: "omnivore",
      wellness_philosophy: "western_integrative",
      dosha: null,
      goals: ["Heart health", "Weight management", "Energy"],
      allergies: ["Shellfish"],
      dislikes: ["Bitter melon", "Liver"],
      loves: ["Salmon", "Berries", "Oats", "Dark chocolate"],
      cuisine_prefs: ["American", "Mediterranean", "Japanese"],
      health_conditions: ["Elevated cholesterol"],
      current_supplements: ["Omega-3", "CoQ10"],
      supplements_open: true,
    },
    {
      id: "demo-member-003",
      name: "Sofia",
      age: 16,
      life_stage: "teen",
      sex: "female",
      activity_level: "very_active",
      dietary_style: "vegetarian",
      wellness_philosophy: "ayurvedic",
      dosha: "vata",
      goals: ["Energy & vitality", "Skin health", "Mental focus"],
      allergies: ["Dairy"],
      dislikes: ["Mushrooms", "Olives"],
      loves: ["Smoothies", "Sweet potato", "Lentils", "Berries"],
      cuisine_prefs: ["Mexican", "Indian", "Mediterranean"],
      health_conditions: [],
      current_supplements: ["B12", "Iron"],
      supplements_open: true,
    },
    {
      id: "demo-member-004",
      name: "Mateo",
      age: 9,
      life_stage: "child",
      sex: "male",
      activity_level: "very_active",
      dietary_style: "omnivore",
      wellness_philosophy: "western_integrative",
      dosha: null,
      goals: ["Energy", "Immune support", "Athletic performance"],
      allergies: ["Peanuts"],
      dislikes: ["Brussels sprouts", "Beets"],
      loves: ["Pasta", "Chicken", "Bananas", "Carrots"],
      cuisine_prefs: ["American", "Italian", "Mexican"],
      health_conditions: [],
      current_supplements: ["Vitamin D", "Zinc"],
      supplements_open: true,
    },
  ],
};

export const DEMO_MEAL_PLAN = {
  id: "demo-plan-001",
  family_id: "demo-family-001",
  week_start: "2026-04-27",
  notes:
    "A balanced week designed for the whole Rivera family — cooling foods for Maria's Pitta, heart-healthy fats for David, grounding Vata-support for Sofia, and protein-rich options for Mateo's active lifestyle.",
  days: [
    {
      day: "Monday",
      breakfast: {
        id: "m-mon-b",
        name: "Coconut Mango Chia Pudding",
        prep_time: 10,
        cook_time: 0,
        cuisine_type: "Fusion",
        tags: ["gluten-free", "dairy-free", "vegan", "make-ahead"],
        ingredients: [
          { name: "Coconut milk", quantity: "1", unit: "can" },
          { name: "Chia seeds", quantity: "4", unit: "tbsp" },
          { name: "Fresh mango", quantity: "1", unit: "large" },
          { name: "Maple syrup", quantity: "1", unit: "tbsp" },
          { name: "Vanilla extract", quantity: "1", unit: "tsp" },
        ],
        instructions: [
          "Whisk coconut milk, chia seeds, maple syrup, and vanilla.",
          "Refrigerate overnight or at least 4 hours.",
          "Top with fresh mango cubes before serving.",
        ],
        why_it_works: {
          Maria: "Cooling coconut milk soothes Pitta; mango supports estrogen metabolism.",
          David: "Chia seeds provide omega-3s and soluble fiber for cholesterol support.",
          Sofia: "Grounding, nourishing start — perfect for Vata energy stabilization.",
          Mateo: "Naturally sweet and easy to customize with extra fruit.",
        },
        member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
      },
      lunch: {
        id: "m-mon-l",
        name: "Mediterranean Lentil Bowl with Herb Tahini",
        prep_time: 15,
        cook_time: 20,
        cuisine_type: "Mediterranean",
        tags: ["gluten-free", "dairy-free", "vegan", "high-protein"],
        ingredients: [
          { name: "French green lentils", quantity: "2", unit: "cups" },
          { name: "Roasted cherry tomatoes", quantity: "2", unit: "cups" },
          { name: "Cucumber", quantity: "1", unit: "large" },
          { name: "Kalamata olives", quantity: "1/4", unit: "cup" },
          { name: "Tahini", quantity: "3", unit: "tbsp" },
          { name: "Fresh parsley & mint", quantity: "1/2", unit: "cup" },
          { name: "Lemon juice", quantity: "2", unit: "tbsp" },
        ],
        instructions: [
          "Cook lentils until tender (18–20 min). Season with cumin and salt.",
          "Blend tahini, lemon juice, garlic, and water into dressing.",
          "Assemble bowls: lentils, veggies, olives, drizzle with herb tahini.",
        ],
        why_it_works: {
          Maria: "Lentils support liver detox pathways important in perimenopause.",
          David: "High soluble fiber directly supports LDL cholesterol reduction.",
          Sofia: "Iron-rich lentils address teen vegetarian iron needs; tahini adds calcium.",
          Mateo: "High protein for active muscles; easy to serve without olives if preferred.",
        },
        member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
      },
      dinner: {
        id: "m-mon-d",
        name: "Baked Salmon with Turmeric Cauliflower & Greens",
        prep_time: 15,
        cook_time: 25,
        cuisine_type: "American",
        tags: ["gluten-free", "dairy-free", "omega-3 rich", "anti-inflammatory"],
        ingredients: [
          { name: "Wild-caught salmon fillets", quantity: "2", unit: "lbs" },
          { name: "Cauliflower", quantity: "1", unit: "head" },
          { name: "Baby spinach", quantity: "4", unit: "cups" },
          { name: "Garlic", quantity: "4", unit: "cloves" },
          { name: "Turmeric", quantity: "1", unit: "tsp" },
          { name: "Olive oil", quantity: "3", unit: "tbsp" },
          { name: "Lemon", quantity: "1", unit: "whole" },
        ],
        instructions: [
          "Toss cauliflower with turmeric, olive oil, salt. Roast at 425°F for 20 min.",
          "Season salmon with lemon, garlic, olive oil. Bake for 12–14 min.",
          "Sauté spinach with garlic until wilted. Serve everything together.",
        ],
        why_it_works: {
          Maria: "Turmeric reduces inflammation; salmon omega-3s support hormone balance.",
          David: "Salmon is the gold standard for heart-protective omega-3 EPA/DHA.",
          Sofia: "Spinach provides iron and folate; Maria & David eat salmon, Sofia gets extra lentils.",
          Mateo: "Mild flavors, easy to love — cauliflower as a fun roasted veggie.",
        },
        member_compatibility: ["Maria", "David", "Mateo"],
      },
      snacks: [
        {
          id: "m-mon-s1",
          name: "Apple slices with almond butter",
          prep_time: 3,
          cook_time: 0,
          cuisine_type: "Snack",
          tags: ["gluten-free", "dairy-free", "quick"],
          ingredients: [
            { name: "Apples", quantity: "2", unit: "medium" },
            { name: "Almond butter", quantity: "4", unit: "tbsp" },
          ],
          instructions: ["Slice apples. Serve with almond butter for dipping."],
          why_it_works: {
            Maria: "Stable blood sugar supports hormonal equilibrium.",
            David: "Pectin in apple skin supports cholesterol management.",
            Sofia: "Grounding, satisfying snack for Vata energy dips.",
            Mateo: "Protein + carb combo for sustained energy post-school.",
          },
          member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
        },
      ],
    },
    {
      day: "Tuesday",
      breakfast: {
        id: "m-tue-b",
        name: "Warm Spiced Oatmeal with Berries",
        prep_time: 5,
        cook_time: 10,
        cuisine_type: "American",
        tags: ["dairy-free option", "heart-healthy", "high-fiber"],
        ingredients: [
          { name: "Rolled oats (GF certified for Maria)", quantity: "2", unit: "cups" },
          { name: "Mixed berries (fresh or frozen)", quantity: "2", unit: "cups" },
          { name: "Cinnamon", quantity: "1", unit: "tsp" },
          { name: "Cardamom", quantity: "1/2", unit: "tsp" },
          { name: "Almond milk", quantity: "2", unit: "cups" },
          { name: "Walnuts", quantity: "1/4", unit: "cup" },
          { name: "Honey or maple syrup", quantity: "1", unit: "tbsp" },
        ],
        instructions: [
          "Simmer oats in almond milk with cinnamon and cardamom until creamy.",
          "Top with berries, walnuts, and a drizzle of honey.",
        ],
        why_it_works: {
          Maria: "Cardamom kindles Agni (digestive fire); berries are cooling and anti-inflammatory.",
          David: "Beta-glucan in oats is clinically proven to reduce LDL cholesterol.",
          Sofia: "Warming spices support Vata digestion; iron from oats for teen needs.",
          Mateo: "Kid-friendly with natural sweetness; walnuts add brain-healthy DHA.",
        },
        member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
      },
      lunch: {
        id: "m-tue-l",
        name: "Chicken & Avocado Power Salad",
        prep_time: 15,
        cook_time: 12,
        cuisine_type: "American",
        tags: ["gluten-free", "dairy-free", "high-protein"],
        ingredients: [
          { name: "Grilled chicken breast", quantity: "1.5", unit: "lbs" },
          { name: "Mixed greens", quantity: "6", unit: "cups" },
          { name: "Avocado", quantity: "2", unit: "medium" },
          { name: "Cherry tomatoes", quantity: "1", unit: "cup" },
          { name: "Pumpkin seeds", quantity: "1/4", unit: "cup" },
          { name: "Olive oil & apple cider vinegar", quantity: "2", unit: "tbsp each" },
        ],
        instructions: [
          "Season and grill chicken. Slice thinly.",
          "Arrange greens, tomatoes, avocado. Top with chicken and seeds.",
          "Dress with olive oil and ACV.",
        ],
        why_it_works: {
          Maria: "Avocado provides healthy fats that support estrogen balance.",
          David: "Monounsaturated fats from avocado + olive oil support HDL.",
          Sofia: "Add extra pumpkin seeds for zinc — key for teen skin health.",
          Mateo: "High protein for muscle recovery after sports.",
        },
        member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
      },
      dinner: {
        id: "m-tue-d",
        name: "Black Bean Tacos with Mango Salsa",
        prep_time: 20,
        cook_time: 15,
        cuisine_type: "Mexican",
        tags: ["gluten-free option", "vegetarian", "family-favorite"],
        ingredients: [
          { name: "Black beans (canned)", quantity: "2", unit: "cans" },
          { name: "Corn tortillas", quantity: "12", unit: "small" },
          { name: "Mango", quantity: "1", unit: "large" },
          { name: "Red onion", quantity: "1/2", unit: "medium" },
          { name: "Jalapeño", quantity: "1", unit: "small" },
          { name: "Cilantro", quantity: "1/2", unit: "cup" },
          { name: "Lime", quantity: "2", unit: "whole" },
          { name: "Cumin & chili powder", quantity: "1", unit: "tsp each" },
        ],
        instructions: [
          "Season and warm black beans with cumin and chili.",
          "Dice mango, red onion, jalapeño. Mix with lime and cilantro for salsa.",
          "Warm tortillas. Assemble tacos with beans and salsa.",
        ],
        why_it_works: {
          Maria: "Cooling mango and cilantro balance Pitta; beans support estrogen metabolism.",
          David: "Bean fiber supports heart health; a plant-forward night is ideal.",
          Sofia: "Fully vegetarian and Vata-grounding with warm spiced beans.",
          Mateo: "Kid-loved format; customize with or without jalapeño.",
        },
        member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
      },
      snacks: [
        {
          id: "m-tue-s1",
          name: "Carrot sticks & hummus",
          prep_time: 5,
          cook_time: 0,
          cuisine_type: "Snack",
          tags: ["vegan", "gluten-free", "quick"],
          ingredients: [
            { name: "Carrots", quantity: "3", unit: "large" },
            { name: "Hummus", quantity: "1/2", unit: "cup" },
          ],
          instructions: ["Cut carrots into sticks. Serve with hummus."],
          why_it_works: {
            Maria: "Beta-carotene supports skin and immune function.",
            David: "Fiber-rich snack that keeps blood sugar stable.",
            Sofia: "Grounding root vegetable — excellent for Vata.",
            Mateo: "Crunchy and fun — Mateo's favorite afternoon snack.",
          },
          member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
        },
      ],
    },
    {
      day: "Wednesday",
      breakfast: {
        id: "m-wed-b",
        name: "Green Goddess Smoothie Bowl",
        prep_time: 10,
        cook_time: 0,
        cuisine_type: "Fusion",
        tags: ["vegan", "gluten-free", "dairy-free", "antioxidant-rich"],
        ingredients: [
          { name: "Frozen spinach", quantity: "2", unit: "cups" },
          { name: "Frozen mango", quantity: "1", unit: "cup" },
          { name: "Banana", quantity: "2", unit: "medium" },
          { name: "Coconut water", quantity: "1/2", unit: "cup" },
          { name: "Hemp seeds", quantity: "2", unit: "tbsp" },
          { name: "Granola (GF)", quantity: "1/4", unit: "cup" },
          { name: "Fresh kiwi", quantity: "2", unit: "small" },
        ],
        instructions: [
          "Blend spinach, mango, banana, coconut water until smooth.",
          "Pour into bowls. Top with granola, hemp seeds, kiwi.",
        ],
        why_it_works: {
          Maria: "Spinach provides folate and magnesium — both drop in perimenopause.",
          David: "Low-calorie density, high nutrients — excellent for weight management.",
          Sofia: "Banana adds grounding energy for Vata; hemp seeds add complete protein.",
          Mateo: "Fun colorful bowl he'll actually get excited about.",
        },
        member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
      },
      lunch: {
        id: "m-wed-l",
        name: "Turkey & Quinoa Stuffed Peppers",
        prep_time: 20,
        cook_time: 30,
        cuisine_type: "American",
        tags: ["gluten-free", "dairy-free", "high-protein", "batch-cook"],
        ingredients: [
          { name: "Bell peppers", quantity: "4", unit: "large" },
          { name: "Ground turkey", quantity: "1", unit: "lb" },
          { name: "Quinoa (cooked)", quantity: "2", unit: "cups" },
          { name: "Black beans", quantity: "1", unit: "can" },
          { name: "Diced tomatoes", quantity: "1", unit: "can" },
          { name: "Cumin & paprika", quantity: "1", unit: "tsp each" },
          { name: "Fresh cilantro", quantity: "1/4", unit: "cup" },
        ],
        instructions: [
          "Brown turkey with spices. Mix with quinoa, beans, tomatoes.",
          "Stuff into halved peppers. Bake at 375°F for 25 min.",
          "Garnish with cilantro.",
        ],
        why_it_works: {
          Maria: "Quinoa is a complete protein and naturally gluten-free.",
          David: "Lean turkey reduces saturated fat vs. beef without sacrificing satisfaction.",
          Sofia: "Use extra quinoa and beans for a vegetarian version of the filling.",
          Mateo: "Interactive and colorful — easy to customize toppings.",
        },
        member_compatibility: ["Maria", "David", "Mateo"],
      },
      dinner: {
        id: "m-wed-d",
        name: "Kitchari (Ayurvedic Cleansing Bowl)",
        prep_time: 10,
        cook_time: 30,
        cuisine_type: "Indian",
        tags: ["vegan", "gluten-free", "dairy-free", "tridoshic", "restorative"],
        ingredients: [
          { name: "Split yellow mung dal", quantity: "1", unit: "cup" },
          { name: "Basmati rice", quantity: "1/2", unit: "cup" },
          { name: "Ghee or coconut oil", quantity: "2", unit: "tbsp" },
          { name: "Cumin seeds", quantity: "1", unit: "tsp" },
          { name: "Turmeric", quantity: "1", unit: "tsp" },
          { name: "Ginger (fresh)", quantity: "1", unit: "inch" },
          { name: "Zucchini & kale", quantity: "2", unit: "cups" },
          { name: "Cilantro & lime", quantity: "to taste", unit: "" },
        ],
        instructions: [
          "Bloom cumin seeds in ghee. Add ginger, turmeric.",
          "Add rinsed mung dal and rice. Add 4 cups water. Simmer 25 min.",
          "Add zucchini and kale in last 5 min. Serve with cilantro and lime.",
        ],
        why_it_works: {
          Maria: "Kitchari is the Ayurvedic gold standard for cleansing and Pitta-balancing.",
          David: "Light, highly digestible, low-inflammatory meal for midweek reset.",
          Sofia: "Warming and deeply grounding for Vata — the ideal Wednesday reset meal.",
          Mateo: "Mild and comforting — serve with a side of his favorite bread.",
        },
        member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
      },
      snacks: [
        {
          id: "m-wed-s1",
          name: "Banana with sunflower seed butter",
          prep_time: 2,
          cook_time: 0,
          cuisine_type: "Snack",
          tags: ["peanut-free", "dairy-free", "gluten-free"],
          ingredients: [
            { name: "Bananas", quantity: "2", unit: "medium" },
            { name: "Sunflower seed butter", quantity: "4", unit: "tbsp" },
          ],
          instructions: ["Slice banana. Serve with sunflower seed butter."],
          why_it_works: {
            Maria: "Potassium in banana supports fluid balance.",
            David: "Great pre-workout fuel without refined sugar.",
            Sofia: "Grounding and energizing for Vata afternoons.",
            Mateo: "Safe for school (peanut-free) and totally kid-approved.",
          },
          member_compatibility: ["Maria", "David", "Sofia", "Mateo"],
        },
      ],
    },
  ],
};

export const DEMO_GROCERY_LIST = {
  id: "demo-grocery-001",
  family_id: "demo-family-001",
  meal_plan_id: "demo-plan-001",
  total_estimated_cost: 218.5,
  budget_weekly: 275,
  items: [
    // Produce
    { id: "g-001", name: "Baby spinach", quantity: 2, unit: "bags (5 oz)", category: "produce", estimated_cost: 7.98, quality_flag: "organic", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-002", name: "Fresh mango", quantity: 3, unit: "large", category: "produce", estimated_cost: 5.97, quality_flag: "conventional", member_tags: ["Maria", "Sofia"], money_saving_tip: "Buy frozen if out of season — same nutrition, lower cost.", checked: false },
    { id: "g-003", name: "Mixed berries (fresh)", quantity: 2, unit: "pints", category: "produce", estimated_cost: 11.98, quality_flag: "organic", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: "Frozen organic berries are equally nutritious and ~40% cheaper.", checked: false },
    { id: "g-004", name: "Avocados", quantity: 4, unit: "medium", category: "produce", estimated_cost: 7.96, quality_flag: "conventional", member_tags: ["Maria", "David"], money_saving_tip: null, checked: false },
    { id: "g-005", name: "Cherry tomatoes", quantity: 2, unit: "pints", category: "produce", estimated_cost: 7.98, quality_flag: "organic", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-006", name: "Bell peppers (mixed)", quantity: 6, unit: "large", category: "produce", estimated_cost: 8.94, quality_flag: "conventional", member_tags: ["David", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-007", name: "Cauliflower", quantity: 1, unit: "head", category: "produce", estimated_cost: 3.99, quality_flag: "conventional", member_tags: ["Maria", "David"], money_saving_tip: null, checked: false },
    { id: "g-008", name: "Zucchini", quantity: 3, unit: "medium", category: "produce", estimated_cost: 3.57, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-009", name: "Kale", quantity: 1, unit: "bunch", category: "produce", estimated_cost: 2.99, quality_flag: "organic", member_tags: ["Maria", "Sofia"], money_saving_tip: null, checked: false },
    { id: "g-010", name: "Carrots", quantity: 2, unit: "lbs", category: "produce", estimated_cost: 2.49, quality_flag: "conventional", member_tags: ["Mateo", "Maria"], money_saving_tip: "Buy whole, not baby — same nutrition at half the price.", checked: false },
    { id: "g-011", name: "Bananas", quantity: 6, unit: "medium", category: "produce", estimated_cost: 1.98, quality_flag: "conventional", member_tags: ["Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-012", name: "Cucumber", quantity: 2, unit: "large", category: "produce", estimated_cost: 3.18, quality_flag: "conventional", member_tags: ["Maria", "David"], money_saving_tip: null, checked: false },
    { id: "g-013", name: "Lemon & lime", quantity: 6, unit: "whole", category: "produce", estimated_cost: 3.0, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-014", name: "Ginger root (fresh)", quantity: 1, unit: "piece (4 oz)", category: "produce", estimated_cost: 1.99, quality_flag: "conventional", member_tags: ["Maria", "Sofia"], money_saving_tip: null, checked: false },
    { id: "g-015", name: "Garlic", quantity: 1, unit: "bulb", category: "produce", estimated_cost: 0.79, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-016", name: "Kiwi", quantity: 4, unit: "small", category: "produce", estimated_cost: 3.96, quality_flag: "conventional", member_tags: ["Sofia", "Mateo"], money_saving_tip: null, checked: false },
    // Proteins
    { id: "g-017", name: "Wild-caught salmon fillets", quantity: 2, unit: "lbs", category: "protein", estimated_cost: 26.0, quality_flag: "specialty", member_tags: ["Maria", "David", "Mateo"], money_saving_tip: "Buy frozen wild-caught — same omega-3 content as fresh, 30% cheaper.", checked: false },
    { id: "g-018", name: "Ground turkey (lean)", quantity: 1, unit: "lb", category: "protein", estimated_cost: 6.99, quality_flag: "conventional", member_tags: ["David", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-019", name: "Chicken breasts", quantity: 2, unit: "lbs", category: "protein", estimated_cost: 11.98, quality_flag: "conventional", member_tags: ["David", "Mateo"], money_saving_tip: null, checked: false },
    // Pantry
    { id: "g-020", name: "French green lentils", quantity: 1, unit: "bag (1 lb)", category: "pantry", estimated_cost: 3.49, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia"], money_saving_tip: null, checked: false },
    { id: "g-021", name: "Black beans (canned)", quantity: 4, unit: "cans", category: "pantry", estimated_cost: 5.16, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: "Buy dried for 50% savings — soak overnight, cook in batches.", checked: false },
    { id: "g-022", name: "Split yellow mung dal", quantity: 1, unit: "bag (1 lb)", category: "pantry", estimated_cost: 3.99, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-023", name: "Quinoa", quantity: 1, unit: "bag (2 lbs)", category: "pantry", estimated_cost: 7.99, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia"], money_saving_tip: null, checked: false },
    { id: "g-024", name: "Basmati rice", quantity: 1, unit: "bag (2 lbs)", category: "pantry", estimated_cost: 4.99, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-025", name: "Rolled oats (GF certified)", quantity: 1, unit: "container (42 oz)", category: "pantry", estimated_cost: 5.49, quality_flag: "specialty", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: "★ GF certification is important for Maria's gluten sensitivity.", checked: false },
    { id: "g-026", name: "Tahini", quantity: 1, unit: "jar (16 oz)", category: "pantry", estimated_cost: 7.99, quality_flag: "conventional", member_tags: ["Maria", "Sofia"], money_saving_tip: null, checked: false },
    { id: "g-027", name: "Almond butter", quantity: 1, unit: "jar (16 oz)", category: "pantry", estimated_cost: 8.99, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: "Costco/bulk store has this at ~50% savings.", checked: false },
    { id: "g-028", name: "Sunflower seed butter", quantity: 1, unit: "jar (16 oz)", category: "pantry", estimated_cost: 7.49, quality_flag: "conventional", member_tags: ["Mateo"], money_saving_tip: "Safe for peanut-free school environments.", checked: false },
    { id: "g-029", name: "Coconut milk (canned)", quantity: 3, unit: "cans", category: "pantry", estimated_cost: 8.97, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-030", name: "Chia seeds", quantity: 1, unit: "bag (12 oz)", category: "pantry", estimated_cost: 6.99, quality_flag: "conventional", member_tags: ["Maria", "David"], money_saving_tip: null, checked: false },
    { id: "g-031", name: "Hemp seeds", quantity: 1, unit: "bag (8 oz)", category: "pantry", estimated_cost: 8.49, quality_flag: "conventional", member_tags: ["Sofia", "Maria"], money_saving_tip: null, checked: false },
    { id: "g-032", name: "Pumpkin seeds", quantity: 1, unit: "bag (8 oz)", category: "pantry", estimated_cost: 4.99, quality_flag: "conventional", member_tags: ["Sofia", "David"], money_saving_tip: null, checked: false },
    { id: "g-033", name: "Walnuts", quantity: 1, unit: "bag (8 oz)", category: "pantry", estimated_cost: 6.99, quality_flag: "conventional", member_tags: ["David", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-034", name: "Turmeric", quantity: 1, unit: "jar", category: "pantry", estimated_cost: 3.49, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-035", name: "Cumin (seeds & ground)", quantity: 1, unit: "jar each", category: "pantry", estimated_cost: 4.98, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    // Dairy & Alternatives
    { id: "g-036", name: "Almond milk (unsweetened)", quantity: 2, unit: "cartons (32 oz)", category: "dairy", estimated_cost: 7.18, quality_flag: "conventional", member_tags: ["Maria", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-037", name: "Coconut water", quantity: 2, unit: "cartons (32 oz)", category: "dairy", estimated_cost: 7.98, quality_flag: "conventional", member_tags: ["Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-038", name: "Hummus", quantity: 2, unit: "containers (10 oz)", category: "dairy", estimated_cost: 7.98, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: "Make at home from canned chickpeas — saves ~60% per batch.", checked: false },
    // Grains & Bread
    { id: "g-039", name: "Corn tortillas (small, GF)", quantity: 1, unit: "pack (30 ct)", category: "grains", estimated_cost: 3.99, quality_flag: "conventional", member_tags: ["Maria", "David", "Sofia", "Mateo"], money_saving_tip: null, checked: false },
    { id: "g-040", name: "GF granola", quantity: 1, unit: "bag (12 oz)", category: "grains", estimated_cost: 6.49, quality_flag: "specialty", member_tags: ["Maria", "Sofia"], money_saving_tip: null, checked: false },
  ],
};

export const DEMO_SUPPLEMENTS = {
  "demo-member-001": {
    member_name: "Maria",
    recommendations: [
      {
        name: "Shatavari (Asparagus racemosus)",
        purpose: "Supports hormonal balance and eases perimenopausal transitions",
        dose_range: "500–1000 mg/day",
        timing: "With breakfast",
        approach: "Ayurvedic",
        contraindication_notes: "Generally well-tolerated. Consult provider if on hormone therapy.",
        form: "capsule",
      },
      {
        name: "Magnesium Glycinate",
        purpose: "Sleep quality, stress resilience, muscle relaxation",
        dose_range: "300–400 mg/day",
        timing: "30–60 min before bed",
        approach: "Western integrative",
        contraindication_notes: "May interact with certain antibiotics. Already taking — confirm current dose.",
        form: "capsule",
      },
      {
        name: "Ashwagandha (KSM-66®)",
        purpose: "Adaptogen for cortisol regulation and Pitta stress management",
        dose_range: "300–600 mg/day",
        timing: "With dinner",
        approach: "Ayurvedic",
        contraindication_notes: "Avoid in pregnancy. May potentiate thyroid medications.",
        form: "capsule",
      },
      {
        name: "Vitamin D3 + K2",
        purpose: "Bone density support (critical in perimenopause), immune function",
        dose_range: "2000–4000 IU D3 + 100 mcg K2/day",
        timing: "With a fat-containing meal",
        approach: "Western integrative",
        contraindication_notes: "Already taking D3 — adding K2 improves calcium direction to bones.",
        form: "capsule",
      },
    ],
  },
  "demo-member-002": {
    member_name: "David",
    recommendations: [
      {
        name: "Omega-3 Fish Oil (EPA+DHA)",
        purpose: "Cardiovascular protection, LDL reduction, anti-inflammatory",
        dose_range: "2–4 g EPA+DHA/day",
        timing: "With meals to reduce fishy aftertaste",
        approach: "Western integrative",
        contraindication_notes: "Already taking — ensure current dose reaches 2g+ EPA+DHA combined. May thin blood at high doses.",
        form: "capsule",
      },
      {
        name: "Berberine",
        purpose: "LDL and blood sugar regulation, cardiovascular support",
        dose_range: "500 mg, 2–3x/day",
        timing: "Before meals",
        approach: "Western integrative",
        contraindication_notes: "Consult provider — can interact with certain medications and may lower blood sugar significantly.",
        form: "capsule",
      },
      {
        name: "CoQ10 (Ubiquinol form)",
        purpose: "Mitochondrial energy, heart muscle support",
        dose_range: "200–300 mg/day",
        timing: "With a fat-containing meal",
        approach: "Western integrative",
        contraindication_notes: "Already taking — ensure ubiquinol form for better absorption over 40.",
        form: "capsule",
      },
      {
        name: "Red Yeast Rice",
        purpose: "Natural statin-like support for cholesterol management",
        dose_range: "600–1200 mg/day",
        timing: "With evening meal",
        approach: "TCM / Western integrative",
        contraindication_notes: "⚠ Do NOT combine with prescription statins. Must be discussed with cardiologist.",
        form: "capsule",
      },
    ],
  },
  "demo-member-003": {
    member_name: "Sofia",
    recommendations: [
      {
        name: "Iron Bisglycinate",
        purpose: "Support for vegetarian teen iron levels — energy, focus, skin",
        dose_range: "18–25 mg/day",
        timing: "On empty stomach with vitamin C (e.g., orange juice)",
        approach: "Western integrative",
        contraindication_notes: "Already supplementing — bisglycinate form is gentler on the stomach. Get levels checked annually.",
        form: "capsule",
      },
      {
        name: "Vitamin B12 (Methylcobalamin)",
        purpose: "Energy metabolism, nerve function — essential for vegetarians",
        dose_range: "1000 mcg/day",
        timing: "With breakfast",
        approach: "Western integrative",
        contraindication_notes: "Already taking — confirm methylcobalamin form (not cyanocobalamin) for best absorption.",
        form: "sublingual tablet",
      },
      {
        name: "Brahmi (Bacopa monnieri)",
        purpose: "Mental clarity, focus, and memory — Ayurvedic brain tonic",
        dose_range: "300–450 mg/day",
        timing: "With breakfast",
        approach: "Ayurvedic",
        contraindication_notes: "Takes 4–8 weeks for cognitive effects to build. Avoid if taking thyroid medications.",
        form: "capsule",
      },
      {
        name: "Zinc (Zinc Picolinate)",
        purpose: "Skin health, immune function, hormone support for teens",
        dose_range: "15–25 mg/day",
        timing: "With food",
        approach: "Western integrative",
        contraindication_notes: "Take separately from iron (2+ hours apart) — they compete for absorption.",
        form: "capsule",
      },
    ],
  },
  "demo-member-004": {
    member_name: "Mateo",
    recommendations: [
      {
        name: "Vitamin D3",
        purpose: "Immune support, bone development, athletic recovery",
        dose_range: "1000–2000 IU/day (child dose)",
        timing: "With a fat-containing meal",
        approach: "Western integrative",
        contraindication_notes: "Already taking — confirm appropriate pediatric dose with pediatrician.",
        form: "gummy or liquid",
      },
      {
        name: "Zinc (child dose)",
        purpose: "Immune function, growth support, wound healing",
        dose_range: "5–10 mg/day",
        timing: "With food",
        approach: "Western integrative",
        contraindication_notes: "Already supplementing — confirm pediatric dose. Excess zinc can deplete copper.",
        form: "gummy",
      },
      {
        name: "Probiotic (child-specific strains)",
        purpose: "Gut health, immune resilience, post-antibiotic recovery",
        dose_range: "5–10 billion CFU/day",
        timing: "With breakfast",
        approach: "Western integrative",
        contraindication_notes: "Generally very safe for children. Choose strains with L. rhamnosus and Bifidobacterium.",
        form: "gummy or powder",
      },
    ],
  },
};
